blank_issues_enabled: false
contact_links: []

# PR 템플릿 선택 화면을 위한 설정
pull_request_templates:
  - name: General Pull Request
    description: For most feature, fix, or refactor updates.
    filename: default.md

  - name: Dev to Main Merge
    description: For merging the dev branch into main for release.
    filename: release.md
