title: "[BUG] "
body:
  - type: input
    id: os
    attributes:
      label: OS / Browser Info
      description: Please specify your operating system or browser version.
      placeholder: e.g. Windows 11 / Chrome 114
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please describe how to reproduce the issue in detail.
      placeholder: |
        1. Go to the main page
        2. Click the button
        3. Error occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
