name: 📝 문서 개선
description: 문서나 README에 대한 개선 사항을 제안해주세요.
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: textarea
    id: what
    attributes:
      label: 개선할 문서
      description: 어떤 문서(파일 또는 섹션)를 개선하고 싶은가요?
      placeholder: 예) README 설치 방법 설명이 부족함
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: 개선 제안
      description: 어떻게 바꾸면 좋을지 적어주세요.
    validations:
      required: true
