name: ✨ 기능 제안
description: 필요한 기능이나 개선사항을 제안해주세요.
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: what
    attributes:
      label: 어떤 기능인가요?
      description: 원하는 기능을 설명해주세요.
      placeholder: 예) 채팅창에 메시지 삭제 기능 추가
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: 왜 필요하나요?
      description: 이 기능이 왜 필요한지 또는 어떤 문제를 해결할 수 있는지 설명해주세요.
    validations:
      required: false
