name: ❓ Question
description: Ask a question or request clarification.
title: "[QUESTION] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to ask?
      placeholder: Please write your question here.
    validations:
      required: true
