import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';

import UserIcon from '../components/UserIcon';
import ArchiveIcon from '../components/ArchiveIcon';


export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>HAMABI Chat</title>
      </head>
      <body>
        <div className="app-container">
          <header className="navbar">
            <Link href="/user" className="icon-button">
              <UserIcon />
            </Link>
            <h1 className="title">HAMABI Chat</h1>
            <Link href="/archive" className="icon-button">
              <ArchiveIcon />
            </Link>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}